import jsPDF from "jspdf";
import { Itinerary } from "@/lib/types";

interface TripPdfData {
  destination: string;
  origin?: string;
  startDate: string;
  endDate: string;
  budget: string;
  itinerary: Itinerary;
}

const MARGIN = 15;
const PAGE_WIDTH = 210; // A4 mm
const PAGE_HEIGHT = 297;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;

export function generateTripPdf({ destination, origin, startDate, endDate, budget, itinerary }: TripPdfData) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  let y = MARGIN;

  function checkPageBreak(neededSpace: number) {
    if (y + neededSpace > PAGE_HEIGHT - MARGIN) {
      doc.addPage();
      y = MARGIN;
    }
  }

  function addWrappedText(text: string, x: number, fontSize: number, style: "normal" | "bold" = "normal", lineHeight = 5) {
    doc.setFontSize(fontSize);
    doc.setFont("helvetica", style);
    const lines = doc.splitTextToSize(text, CONTENT_WIDTH - (x - MARGIN));
    checkPageBreak(lines.length * lineHeight);
    doc.text(lines, x, y);
    y += lines.length * lineHeight;
  }

  // Title
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text(destination, MARGIN, y);
  y += 9;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100);
  const subtitle = [
    `${startDate} to ${endDate}`,
    budget,
    origin ? `Departing from ${origin}` : null,
  ].filter(Boolean).join("  •  ");
  doc.text(subtitle, MARGIN, y);
  doc.setTextColor(0);
  y += 10;

  doc.setDrawColor(200);
  doc.line(MARGIN, y, PAGE_WIDTH - MARGIN, y);
  y += 8;

  // Each day
  itinerary.days.forEach((day) => {
    checkPageBreak(20);

    addWrappedText(`Day ${day.day}: ${day.title}`, MARGIN, 14, "bold", 6);
    y += 1;

    doc.setFontSize(10);
    doc.setFont("helvetica", "italic");
    doc.setTextColor(80);
    addWrappedText(`Hotel: ${day.hotelSuggestion}`, MARGIN, 10, "italic", 5);
    doc.setTextColor(0);
    y += 3;

    day.activities.forEach((activity) => {
      checkPageBreak(18);

      doc.setFontSize(10);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(30, 60, 150);
      doc.text(activity.time, MARGIN, y);
      doc.setTextColor(0);

      doc.setFont("helvetica", "bold");
      doc.setFontSize(11);
      doc.text(activity.name, MARGIN + 22, y);

      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.setTextColor(80);
      const costWidth = doc.getTextWidth(activity.estimatedCost);
      doc.text(activity.estimatedCost, PAGE_WIDTH - MARGIN - costWidth, y);
      doc.setTextColor(0);
      y += 5;

      doc.setFontSize(9.5);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(90);
      const descLines = doc.splitTextToSize(activity.description, CONTENT_WIDTH - 22);
      checkPageBreak(descLines.length * 4.5);
      doc.text(descLines, MARGIN + 22, y);
      doc.setTextColor(0);
      y += descLines.length * 4.5 + 4;
    });

    y += 4;
    checkPageBreak(2);
    doc.setDrawColor(230);
    doc.line(MARGIN, y, PAGE_WIDTH - MARGIN, y);
    y += 8;
  });

  // Footer on every page
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(`Generated by Yatra AI  •  Page ${i} of ${pageCount}`, MARGIN, PAGE_HEIGHT - 8);
  }

  const filename = `${destination.replace(/[^a-z0-9]/gi, "_")}_itinerary.pdf`;
  doc.save(filename);
}